import React, { createContext, useContext, useState } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English (India)', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
];

const translations = {
  // 1. English (India)
  en: {
    app_title: "SmartVote Bharat",
    app_subtitle: "National Digital E-Voting Portal",
    eci_badge: "Election Commission of India Standard",
    nav_home: "Home",
    nav_elections: "Elections & Ballots",
    nav_verify: "Verify Receipt",
    nav_login: "Citizen Sign In",
    nav_register: "Voter Registration",
    nav_dashboard: "Voter Portal",
    nav_admin: "Admin Hub",
    nav_logout: "Sign Out",
    nav_admin_overview: "Admin Overview",
    nav_admin_elections: "Manage Elections",
    nav_admin_voters: "Electoral Roll",
    nav_admin_audit: "Security Audit",
    hero_badge: "Official National Digital Voting Portal",
    hero_title: "Secure, Verifiable Online Democracy for Every Indian Citizen",
    hero_subtitle: "Empowering Indian democracy with AI biometric liveness verification, multi-factor Aadhaar authentication, and tamper-proof cryptographic receipts under Article 324.",
    hero_cta_vote: "Cast Your Ballot",
    hero_cta_register: "Enroll as a Voter",
    stat_uptime: "System Availability",
    stat_turnout: "Voter Turnout",
    stat_votes: "Sealed Ballots",
    stat_voters: "Registered Citizens",
    stat_active_elections: "Active Elections",
    pillar_1_title: "Biometric Liveness Verification",
    pillar_1_desc: "Browser-native AI facial analysis confirms genuine citizen presence and anti-spoofing liveness before ballot issuance, strictly enforcing one citizen, one vote.",
    pillar_2_title: "Multi-Factor Identity Verification",
    pillar_2_desc: "Encrypted one-time passcode (OTP) delivered to the voter's registered mobile number to confirm authenticated possession of electoral credentials.",
    pillar_3_title: "Cryptographic Ballot Receipts",
    pillar_3_desc: "Every ballot cast produces an immutable SHA-256 digital certificate with a verifiable QR seal, allowing citizens to audit their vote without revealing candidate choice.",
    election_active: "Active Election",
    election_upcoming: "Upcoming Poll",
    election_completed: "Polls Concluded",
    btn_vote_now: "Vote Now",
    btn_cast_ballot: "Cast Ballot",
    btn_access_ballot: "Access Ballot",
    btn_view_details: "View Details",
    btn_download_pdf: "Download Official Certificate (PDF)",
    btn_return_dashboard: "Return to Dashboard",
    btn_retake_photo: "Retake Photo",
    btn_take_photo: "Take Photo Now",
    face_scanning: "Scanning Facial Biometrics...",
    face_blink_prompt: "Please blink naturally",
    face_turn_prompt: "Turn head slightly to the right",
    face_look_straight: "Look straight into the camera",
    face_verified: "Biometric Identity Confirmed",
    face_enroll_title: "Official Biometric Photo Enrollment",
    face_verify_title: "Biometric Identity Verification",
    receipt_title: "Official Voting Certificate",
    receipt_hash: "SHA-256 Cryptographic Seal",
    receipt_verified: "Receipt Authenticated on Ledger",
    notice_secret_ballot: "Constitutional Secret Ballot Protection (Article 324, Constitution of India)",
    helpline_text: "National Voter Helpline: Toll-Free 1950",
  },

  // 2. Hindi (हिन्दी)
  hi: {
    app_title: "स्मार्टवोट भारत",
    app_subtitle: "राष्ट्रीय डिजिटल मतदान पोर्टल",
    eci_badge: "भारत निर्वाचन आयोग मानक",
    nav_home: "होम",
    nav_elections: "चुनाव एवं मतपत्र",
    nav_verify: "रसीद सत्यापित करें",
    nav_login: "नागरिक लॉग इन",
    nav_register: "मतदाता पंजीकरण",
    nav_dashboard: "मतदाता पोर्टल",
    nav_admin: "एडमिन हब",
    nav_logout: "लॉग आउट",
    nav_admin_overview: "एडमिन अवलोकन",
    nav_admin_elections: "चुनाव प्रबंधन",
    nav_admin_voters: "मतदाता सूची",
    nav_admin_audit: "सुरक्षा ऑडिट",
    hero_badge: "आधिकारिक राष्ट्रीय डिजिटल मतदान पोर्टल",
    hero_title: "प्रत्येक भारतीय नागरिक के लिए सुरक्षित एवं पारदर्शी ई-मतदान",
    hero_subtitle: "अनुच्छेद 324 के अंतर्गत एआई बायोमेट्रिक सत्यापन, दोहरे कारक प्रमाणीकरण और अपरिवर्तनीय डिजिटल रसीद द्वारा भारतीय लोकतंत्र को सशक्त बनाना।",
    hero_cta_vote: "मतदान करें",
    hero_cta_register: "मतदाता के रूप में पंजीकरण करें",
    stat_uptime: "प्रणाली उपलब्धता",
    stat_turnout: "मतदान प्रतिशत",
    stat_votes: "सील किए गए मतपत्र",
    stat_voters: "पंजीकृत नागरिक",
    stat_active_elections: "सक्रिय चुनाव",
    pillar_1_title: "बायोमेट्रिक लाइवनेस सत्यापन",
    pillar_1_desc: "ब्राउज़र-आधारित एआई फेशियल विश्लेषण फर्जी मतदान रोकने के लिए प्राकृतिक पलक झपकाने और चेहरे की गतिविधियों की पुष्टि करता है।",
    pillar_2_title: "मल्टी-फैक्टर प्रमाणीकरण",
    pillar_2_desc: "मतदाता के पंजीकृत मोबाइल नंबर पर सुरक्षित ओटीपी भेजकर वास्तविक नागरिक पहचान की पुष्टि की जाती है।",
    pillar_3_title: "क्रिप्टोग्राफिक डिजिटल रसीद",
    pillar_3_desc: "प्रत्येक डाले गए वोट पर अपरिवर्तनीय SHA-256 डिजिटल मुहर लगती है, जिससे बिना वोट का खुलासा किए पूर्ण गोपनीयता बनी रहती है।",
    election_active: "सक्रिय चुनाव",
    election_upcoming: "आगामी चुनाव",
    election_completed: "मतदान संपन्न",
    btn_vote_now: "अभी वोट दें",
    btn_cast_ballot: "वोट डालें",
    btn_access_ballot: "मतपत्र देखें",
    btn_view_details: "विवरण देखें",
    btn_download_pdf: "आधिकारिक प्रमाण पत्र डाउनलोड करें (PDF)",
    btn_return_dashboard: "डैशबोर्ड पर लौटें",
    btn_retake_photo: "दोबारा फोटो लें",
    btn_take_photo: "अभी फोटो लें",
    face_scanning: "चेहरा स्कैन हो रहा है...",
    face_blink_prompt: "कृपया सामान्य रूप से पलकें झपकाएं",
    face_turn_prompt: "सिर को थोड़ा दाईं ओर घुमाएं",
    face_look_straight: "सीधे कैमरे में देखें",
    face_verified: "बायोमेट्रिक पहचान सत्यापित",
    face_enroll_title: "आधिकारिक बायोमेट्रिक फोटो नामांकन",
    face_verify_title: "बायोमेट्रिक पहचान सत्यापन",
    receipt_title: "आधिकारिक मतदान प्रमाण पत्र",
    receipt_hash: "SHA-256 क्रिप्टोग्राफिक सील",
    receipt_verified: "रसीद लेजर पर सफलतापूर्वक सत्यापित",
    notice_secret_ballot: "संवैधानिक गुप्त मतदान सुरक्षा (अनुच्छेद 324, भारत का संविधान)",
    helpline_text: "राष्ट्रीय मतदाता हेल्पलाइन: टोल-फ्री 1950",
  },

  // 3. Telugu (తెలుగు)
  te: {
    app_title: "స్మార్ట్‌ఓట్ భారత్",
    app_subtitle: "జాతీయ డిజిటల్ ఓటింగ్ పోర్టల్",
    eci_badge: "భారత ఎన్నికల సంఘం ప్రామాణికం",
    nav_home: "హోమ్",
    nav_elections: "ఎన్నికలు & బ్యాలెట్",
    nav_verify: "రసీదు ధృవీకరణ",
    nav_login: "పౌరుల లాగిన్",
    nav_register: "ఓటరు నమోదు",
    nav_dashboard: "ఓటరు పోర్టల్",
    nav_admin: "అడ్మిన్ హబ్",
    nav_logout: "లాగ్ అవుట్",
    nav_admin_overview: "అడ్మిన్ సమీక్ష",
    nav_admin_elections: "ఎన్నికల నిర్వహణ",
    nav_admin_voters: "ఓటర్ల జాబితా",
    nav_admin_audit: "భద్రతా ఆడిట్",
    hero_badge: "అధికారిక జాతీయ డిజిటల్ ఓటింగ్ వేదిక",
    hero_title: "ప్రతి భారతీయ పౌరునికి సురక్షితమైన, పారదర్శక ఈ-ఓటింగ్",
    hero_subtitle: "ఆర్టికల్ 324 ప్రకారం AI బయోమెట్రిక్ లైవ్‌నెస్ ధృవీకరణ, ఆధార్ మొబైల్ OTP మరియు క్రిప్టోగ్రాఫిక్ డిజిటల్ రసీదులతో ప్రజాస్వామ్య సాధికారత.",
    hero_cta_vote: "ఓటు వేయండి",
    hero_cta_register: "ఓటరుగా నమోదు చేసుకోండి",
    stat_uptime: "వ్యవస్థ లభ్యత",
    stat_turnout: "పోలింగ్ శాతం",
    stat_votes: "నమోదైన ఓట్లు",
    stat_voters: "నమోదిత పౌరులు",
    stat_active_elections: "ప్రస్తుత ఎన్నికలు",
    pillar_1_title: "బయోమెట్రిక్ లైవ్‌నెస్ ధృవీకరణ",
    pillar_1_desc: "నకిలీ ఓట్లను నిరోధించడానికి సహజమైన కన్ను మూసి తెరవడం మరియు తల కదలికలను AI ద్వారా కచ్చితంగా గుర్తిస్తుంది.",
    pillar_2_title: "బహుళ-అంచెల ధృవీకరణ",
    pillar_2_desc: "నమోదిత మొబైల్ నంబర్‌కు పంపబడే సురక్షిత OTP ద్వారా నిజమైన ఓటరు హాజరును నిర్ధారిస్తుంది.",
    pillar_3_title: "క్రిప్టోగ్రాఫిక్ డిజిటల్ రసీదు",
    pillar_3_desc: "ప్రతి ఓటుకు SHA-256 డిజిటల్ ముద్ర కేటాయించబడుతుంది, ఓటు గోప్యతను కాపాడుతూ లెడ్జర్‌లో సురక్షితం చేయబడుతుంది.",
    election_active: "ప్రస్తుత ఎన్నిక",
    election_upcoming: "రాబోయే ఎన్నికలు",
    election_completed: "ముగిసిన ఎన్నికలు",
    btn_vote_now: "ఇప్పుడే ఓటు వేయండి",
    btn_cast_ballot: "ఓటు సమర్పించండి",
    btn_access_ballot: "బ్యాలెట్ తెరవండి",
    btn_view_details: "వివరాలు చూడండి",
    btn_download_pdf: "అధికారిక సర్టిఫికేట్ డౌన్‌లోడ్ (PDF)",
    btn_return_dashboard: "డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి",
    btn_retake_photo: "మళ్ళీ ఫోటో తీయండి",
    btn_take_photo: "ఇప్పుడే ఫోటో తీయండి",
    face_scanning: "ముఖం స్కాన్ అవుతోంది...",
    face_blink_prompt: "దయచేసి సహజంగా కళ్ళు ఆర్పండి",
    face_turn_prompt: "తలను కొద్దిగా కుడివైపు తిప్పండి",
    face_look_straight: "కెమెరా వైపు నేరుగా చూడండి",
    face_verified: "బయోమెట్రిక్ గుర్తింపు ధృవీకరించబడింది",
    face_enroll_title: "అధికారిక బయోమెట్రిక్ నమోదు",
    face_verify_title: "బయోమెట్రిక్ ముఖ ధృవీకరణ",
    receipt_title: "అధికారిక ఓటింగ్ ధృవీకరణ పత్రం",
    receipt_hash: "SHA-256 క్రిప్టోగ్రాఫిక్ సీల్",
    receipt_verified: "రసీదు లెడ్జర్‌లో ధృవీకరించబడింది",
    notice_secret_ballot: "రాజ్యాంగబద్ధ రహస్య బ్యాలెట్ రక్షణ (ఆర్టికల్ 324, భారత రాజ్యాంగం)",
    helpline_text: "జాతీయ ఓటర్ హెల్ప్‌లైన్: టోల్-ఫ్రీ 1950",
  },

  // 4. Tamil (தமிழ்)
  ta: {
    app_title: "ஸ்மார்ட்வோட் பாரத்",
    app_subtitle: "தேசிய டிஜிட்டல் வாக்குப்பதிவு தளம்",
    eci_badge: "இந்திய தேர்தல் ஆணைய தரநிலை",
    nav_home: "முகப்பு",
    nav_elections: "தேர்தல்கள் & வாக்குச்சீட்டு",
    nav_verify: "ரசீது சரிபார்த்தல்",
    nav_login: "குடிமக்கள் உள்நுழைவு",
    nav_register: "வாக்காளர் பதிவு",
    nav_dashboard: "வாக்காளர் தளம்",
    nav_admin: "நிர்வாக மையம்",
    nav_logout: "வெளியேறு",
    nav_admin_overview: "நிர்வாக கண்ணோட்டம்",
    nav_admin_elections: "தேர்தல் மேலாண்மை",
    nav_admin_voters: "வாக்காளர் பட்டியல்",
    nav_admin_audit: "பாதுகாப்பு தணிக்கை",
    hero_badge: "அதிகாரப்பூர்வ தேசிய டிஜிட்டல் வாக்குப்பதிவு தளம்",
    hero_title: "ஒவ்வொரு இந்திய குடிமகனுக்கும் பாதுகாப்பான, வெளிப்படையான தேர்தல்",
    hero_subtitle: "பிரிவு 324-ன் கீழ் AI பயோமெட்ரிக் சரிபார்ப்பு, ஆதார் மொபைல் OTP மற்றும் நம்பகமான டிஜிட்டல் ரசீதுகள் மூலம் வாக்குரிமை பாதுகாப்பு.",
    hero_cta_vote: "வாக்களிக்கவும்",
    hero_cta_register: "வாக்காளராக பதிவு செய்யவும்",
    stat_uptime: "கணினி கிடைக்கும் தன்மை",
    stat_turnout: "வாக்குப்பதிவு சதவீதம்",
    stat_votes: "பதிவான வாக்குகள்",
    stat_voters: "பதிவு செய்த குடிமக்கள்",
    stat_active_elections: "செயலில் உள்ள தேர்தல்கள்",
    pillar_1_title: "பயோமெட்ரிக் நேரடி சரிபார்ப்பு",
    pillar_1_desc: "போலி வாக்குகளைத் தடுக்க இயற்கையான கண் சிமிட்டல் மற்றும் முக அசைவுகளை AI உறுதி செய்கிறது.",
    pillar_2_title: "பல காரணி அங்கீகாரம்",
    pillar_2_desc: "பதிவு செய்யப்பட்ட மொபைல் எண்ணிற்கு அனுப்பப்படும் பாதுகாப்பான OTP மூலம் சரியான வாக்காளர் அடையாளம் உறுதிப்படுத்தப்படுகிறது.",
    pillar_3_title: "கிரிப்டோகிராஃபிக் வாக்கு ரசீது",
    pillar_3_desc: "ஒவ்வொரு வாக்கிற்கும் மாற்ற முடியாத SHA-256 டிஜிட்டல் முத்திரை வழங்கப்பட்டு இரகசியத்தன்மை பாதுகாக்கப்படுகிறது.",
    election_active: "செயலில் உள்ள தேர்தல்",
    election_upcoming: "வரவிருக்கும் தேர்தல்",
    election_completed: "தேர்தல் முடிந்தது",
    btn_vote_now: "இப்போது வாக்களிக்கவும்",
    btn_cast_ballot: "வாக்கை பதிவு செய்",
    btn_access_ballot: "வாக்குச்சீட்டை திறக்கவும்",
    btn_view_details: "விவரங்களை காண்க",
    btn_download_pdf: "அதிகாரப்பூர்வ சான்றிதழ் பதிவிறக்கம் (PDF)",
    btn_return_dashboard: "டாஷ்போர்டுக்கு திரும்புக",
    btn_retake_photo: "மீண்டும் புகைப்படம் எடுக்கவும்",
    btn_take_photo: "இப்போது படம் எடுக்கவும்",
    face_scanning: "முகம் ஸ்கேன் செய்யப்படுகிறது...",
    face_blink_prompt: "இயற்கையாக கண்களை சிமிட்டவும்",
    face_turn_prompt: "தலையை வலதுபுறம் சற்று திருப்பவும்",
    face_look_straight: "கேமராவை நேராக பார்க்கவும்",
    face_verified: "பயோமெட்ரிக் அடையாளம் உறுதி செய்யப்பட்டது",
    face_enroll_title: "அதிகாரப்பூர்வ பயோமெட்ரிக் பதிவு",
    face_verify_title: "பயோமெட்ரிக் முக சரிபார்ப்பு",
    receipt_title: "அதிகாரப்பூர்வ வாக்குப்பதிவு சான்றிதழ்",
    receipt_hash: "SHA-256 கிரிப்டோகிராஃபிக் முத்திரை",
    receipt_verified: "ரசீது வெற்றிகரமாக சரிபார்க்கப்பட்டது",
    notice_secret_ballot: "அரசியலமைப்பு இரகசிய வாக்குப்பதிவு பாதுகாப்பு (பிரிவு 324, இந்திய அரசியலமைப்பு)",
    helpline_text: "தேசிய வாக்காளர் உதவி எண்: கட்டணமில்லா 1950",
  },

  // 5. Kannada (ಕನ್ನಡ)
  kn: {
    app_title: "ಸ್ಮಾರ್ಟ್‌ವೋಟ್ ಭಾರತ್",
    app_subtitle: "ರಾಷ್ಟ್ರೀಯ ಡಿಜಿಟಲ್ ಮತದಾನ ಪೋರ್ಟಲ್",
    eci_badge: "ಭಾರತೀಯ ಚುನಾವಣಾ ಆಯೋಗದ ಗುಣಮಟ್ಟ",
    nav_home: "ಮುಖಪುಟ",
    nav_elections: "ಚುನಾವಣೆಗಳು & ಮತಪತ್ರ",
    nav_verify: "ರಶೀದಿ ಪರಿಶೀಲನೆ",
    nav_login: "ನಾಗರಿಕ ಲಾಗಿನ್",
    nav_register: "ಮತದಾರರ ನೋಂದಣಿ",
    nav_dashboard: "ಮತದಾರರ ಪೋರ್ಟಲ್",
    nav_admin: "ನಿರ್ವಾಹಕ ಹಬ್",
    nav_logout: "ಲಾಗ್ ಔಟ್",
    nav_admin_overview: "ಅವಲೋಕನ",
    nav_admin_elections: "ಚುನಾವಣೆ ನಿರ್ವಹಣೆ",
    nav_admin_voters: "ಮತದಾರರ ಪಟ್ಟಿ",
    nav_admin_audit: "ಭದ್ರತಾ ಆಡಿಟ್",
    hero_badge: "ಅಧಿಕೃತ ರಾಷ್ಟ್ರೀಯ ಡಿಜಿಟಲ್ ಮತದಾನ ಪೋರ್ಟಲ್",
    hero_title: "ಪ್ರತಿಯೊಬ್ಬ ಭಾರತೀಯ ನಾಗರಿಕನಿಗೆ ಸುರಕ್ಷಿತ ಮತ್ತು ಪಾರದರ್ಶಕ ಇ-ಮತದಾನ",
    hero_subtitle: "ವಿಧಿ 324 ರ ಅಡಿಯಲ್ಲಿ AI ಬಯೋಮೆಟ್ರಿಕ್ ಮುಖ ಪರಿಶೀಲನೆ, ಆಧಾರ್ ಮೊಬೈಲ್ OTP ಮತ್ತು ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಡಿಜಿಟಲ್ ರಶೀದಿಯೊಂದಿಗೆ ಪ್ರಜಾಪ್ರಭುತ್ವ ಸಬಲೀಕರಣ.",
    hero_cta_vote: "ಮತ ಚಲಾಯಿಸಿ",
    hero_cta_register: "ಮತದಾರರಾಗಿ ನೋಂದಾಯಿಸಿ",
    stat_uptime: "ಸಿಸ್ಟಮ್ ಲಭ್ಯತೆ",
    stat_turnout: "ಮತದಾನ ಶೇಕಡಾವಾರು",
    stat_votes: "ನೋಂದಾಯಿತ ಮತಗಳು",
    stat_voters: "ನೋಂದಾಯಿತ ನಾಗರಿಕರು",
    stat_active_elections: "ಪ್ರಸ್ತುತ ಚುನಾವಣೆಗಳು",
    pillar_1_title: "ಬಯೋಮೆಟ್ರಿಕ್ ಮುಖ ಪರಿಶೀಲನೆ",
    pillar_1_desc: "ನಕಲಿ ಮತದಾನ ತಡೆಯಲು AI ಮೂಲಕ ನೈಸರ್ಗಿಕ ಕಣ್ಣು ಮಿಟುಕಿಸುವಿಕೆ ಮತ್ತು ಮುಖ ಚಲನವಲನಗಳನ್ನು ನಿಖರವಾಗಿ ದೃಢೀಕರಿಸಲಾಗುತ್ತದೆ.",
    pillar_2_title: "ಬಹು-ಅಂಚೆಯ ದೃಢೀಕರಣ",
    pillar_2_desc: "ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ ಕಳುಹಿಸಲಾದ ಸುರಕ್ಷಿತ OTP ಮೂಲಕ ಅಧಿಕೃತ ಮತದಾರರ ಉಪಸ್ಥಿತಿಯನ್ನು ಖಚಿತಪಡಿಸಲಾಗುತ್ತದೆ.",
    pillar_3_title: "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಡಿಜಿಟಲ್ ರಶೀದಿ",
    pillar_3_desc: "ಪ್ರತಿ ಮತಕ್ಕೆ ಶಾಶ್ವತ SHA-256 ಡಿಜಿಟಲ್ ಸೀಲ್ ಲಗತ್ತಿಸಲಾಗಿದ್ದು, ಮತದ ಗೌಪ್ಯತೆಯನ್ನು ರಕ್ಷಿಸಲಾಗುತ್ತದೆ.",
    election_active: "ಸಕ್ರಿಯ ಚುನಾವಣೆ",
    election_upcoming: "ಮುಂಬರುವ ಚುನಾವಣೆ",
    election_completed: "ಮುಕ್ತಾಯಗೊಂಡ ಚುನಾವಣೆ",
    btn_vote_now: "ಈಗಲೇ ಮತ ಚಲಾಯಿಸಿ",
    btn_cast_ballot: "ಮತ ಹಾಕಿ",
    btn_access_ballot: "ಮತಪತ್ರ ವೀಕ್ಷಿಸಿ",
    btn_view_details: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    btn_download_pdf: "ಅಧಿಕೃತ ಪ್ರಮಾಣಪತ್ರ ಡೌನ್‌ಲೋಡ್ (PDF)",
    btn_return_dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    btn_retake_photo: "ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    btn_take_photo: "ಈಗಲೇ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    face_scanning: "ಮುಖ ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    face_blink_prompt: "ದಯವಿಟ್ಟು ನೈಸರ್ಗಿಕವಾಗಿ ಕಣ್ಣು ಮಿಟುಕಿಸಿ",
    face_turn_prompt: "ತಲೆಯನ್ನು ಬಲಕ್ಕೆ ಸ್ವಲ್ಪ ತಿರುಗಿಸಿ",
    face_look_straight: "ಕ್ಯಾಮೆರಾವನ್ನು ನೇರವಾಗಿ ನೋಡಿ",
    face_verified: "ಬಯೋಮೆಟ್ರಿಕ್ ಗುರುತು ದೃಢಪಟ್ಟಿದೆ",
    face_enroll_title: "ಅಧಿಕೃತ ಬಯೋಮೆಟ್ರಿಕ್ ಫೋಟೋ ನೋಂದಣಿ",
    face_verify_title: "ಬಯೋಮೆಟ್ರಿಕ್ ಗುರುತಿನ ಪರಿಶೀಲನೆ",
    receipt_title: "ಅಧಿಕೃತ ಮತದಾನ ಪ್ರಮಾಣಪತ್ರ",
    receipt_hash: "SHA-256 ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸೀಲ್",
    receipt_verified: "ರಶೀದಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    notice_secret_ballot: "ಸಾಂವಿಧಾನಿಕ ರಹಸ್ಯ ಮತದಾನ ರಕ್ಷಣೆ (ವಿಧಿ 324, ಭಾರತದ ಸಂವಿಧಾನ)",
    helpline_text: "ರಾಷ್ಟ್ರೀಯ ಮತದಾರರ ಸಹಾಯವಾಣಿ: ಟೋಲ್-ಫ್ರೀ 1950",
  },

  // 6. Bengali (বাংলা)
  bn: {
    app_title: "স্মার্টভোট ভারত",
    app_subtitle: "জাতীয় ডিজিটাল ই-ভোটিং পোর্টাল",
    eci_badge: "ভারতের নির্বাচন কমিশন মানক",
    nav_home: "হোম",
    nav_elections: "নির্বাচন ও ব্যালট",
    nav_verify: "রসিদ যাচাই করুন",
    nav_login: "নাগরিক লগ ইন",
    nav_register: "ভোটার নিবন্ধন",
    nav_dashboard: "ভোটার পোর্টাল",
    nav_admin: "অ্যাডমিন হাব",
    nav_logout: "লগ আউট",
    nav_admin_overview: "অ্যাডমিন বিবরণ",
    nav_admin_elections: "নির্বাচন পরিচালনা",
    nav_admin_voters: "ভোটার তালিকা",
    nav_admin_audit: "নিরাপত্তা অডিট",
    hero_badge: "অফিসিয়াল জাতীয় ডিজিটাল ভোটিং পোর্টাল",
    hero_title: "প্রতিটি ভারতীয় নাগরিকের জন্য সুরক্ষিত ও স্বচ্ছ ই-ভোটিং",
    hero_subtitle: "অনুচ্ছেদ ৩২৪ এর আওতায় এআই বায়োমেট্রিক মুখের শনাক্তকরণ, আধার মোবাইল ওটিপি এবং নিরাপদ ডিজিটাল রসিদের মাধ্যমে গণতন্ত্রের ক্ষমতায়ন।",
    hero_cta_vote: "ভোট দিন",
    hero_cta_register: "ভোটার হিসেবে নাম নথিভুক্ত করুন",
    stat_uptime: "সিস্টেমের প্রাপ্যতা",
    stat_turnout: "ভোটদানের হার",
    stat_votes: "সিল করা ভোট",
    stat_voters: "নিবন্ধিত নাগরিক",
    stat_active_elections: "সক্রিয় নির্বাচন",
    pillar_1_title: "বায়োমেট্রিক লাইভনেস যাচাইকরণ",
    pillar_1_desc: "ভুয়া ভোট রোধ করতে ব্রাউজার-ভিত্তিক এআই চোখের স্বাভাবিক পলক ও নড়াচড়া নির্ভুলভাবে শনাক্ত করে।",
    pillar_2_title: "বহু-স্তরীয় প্রমাণীকরণ",
    pillar_2_desc: "নিবন্ধিত মোবাইল নম্বরে প্রেরিত সুরক্ষিত ওটিপি-র মাধ্যমে প্রকৃত নাগরিকের উপস্থিতি নিশ্চিত করা হয়।",
    pillar_3_title: "ক্রিপ্টোগ্রাফিক ডিজিটাল রসিদ",
    pillar_3_desc: "প্রতিটি ভোটের জন্য অপরিবর্তনীয় SHA-256 ডিজিটাল সিল তৈরি হয় যা ব্যালটের পূর্ণ গোপনীয়তা বজায় রাখে।",
    election_active: "সক্রিয় নির্বাচন",
    election_upcoming: "আসন্ন নির্বাচন",
    election_completed: "ভোটগ্রহণ সমাপ্ত",
    btn_vote_now: "এখনই ভোট দিন",
    btn_cast_ballot: "ভোট প্রদান করুন",
    btn_access_ballot: "ব্যালট দেখুন",
    btn_view_details: "বিস্তারিত দেখুন",
    btn_download_pdf: "অফিসিয়াল সার্টিফিকেট ডাউনলোড করুন (PDF)",
    btn_return_dashboard: "ড্যাশবোর্ডে ফিরে যান",
    btn_retake_photo: "আবার ছবি তুলুন",
    btn_take_photo: "এখনই ছবি তুলুন",
    face_scanning: "মুখ স্ক্যান করা হচ্ছে...",
    face_blink_prompt: "দয়া করে স্বাভাবিকভাবে চোখের পলক ফেলুন",
    face_turn_prompt: "মাথাটি ডানদিকে সামান্য ঘোরান",
    face_look_straight: "ক্যামেরার দিকে সোজা তাকান",
    face_verified: "বায়োমেট্রিক পরিচয় নিশ্চিত হয়েছে",
    face_enroll_title: "অফিসিয়াল বায়োমেট্রিক ফটো নিবন্ধন",
    face_verify_title: "বায়োমেট্রিক পরিচয় যাচাইকরণ",
    receipt_title: "অফিসিয়াল ভোটিং সার্টিফিকেট",
    receipt_hash: "SHA-256 ক্রিপ্টোগ্রাফিক সিল",
    receipt_verified: "রসিদ লেজারে সফলভাবে যাচাইকৃত",
    notice_secret_ballot: "সাংবিধানিক গোপন ব্যালট সুরক্ষা (অনুচ্ছেদ ৩২৪, ভারতের সংবিধান)",
    helpline_text: "জাতীয় ভোটার হেল্পলাইন: টোল-ফ্রি ১৯৫০",
  },

  // 7. Marathi (मराठी)
  mr: {
    app_title: "स्मार्टव्होट भारत",
    app_subtitle: "राष्ट्रीय डिजिटल मतदान पोर्टल",
    eci_badge: "भारतीय निवडणूक आयोग मानक",
    nav_home: "मुख्यपृष्ठ",
    nav_elections: "निवडणुका व मतपत्रिका",
    nav_verify: "पावती पडताळणी",
    nav_login: "नागरिक लॉगिन",
    nav_register: "मतदार नोंदणी",
    nav_dashboard: "मतदार पोर्टल",
    nav_admin: "प्रशासक हब",
    nav_logout: "लॉग आउट",
    nav_admin_overview: "प्रशासक आढावा",
    nav_admin_elections: "निवडणूक व्यवस्थापन",
    nav_admin_voters: "मतदार यादी",
    nav_admin_audit: "सुरक्षा ऑडिट",
    hero_badge: "अधिकृत राष्ट्रीय डिजिटल मतदान पोर्टल",
    hero_title: "प्रत्येक भारतीय नागरिकासाठी सुरक्षित व पारदर्शक डिजिटल मतदान",
    hero_subtitle: "कलम ३२४ अंतर्गत एआय बायोमेट्रिक पडताळणी, आधार मोबाईल ओटीपी व सुरक्षित डिजिटल पावतीद्वारे भारतीय लोकशाहीचे सक्षमीकरण.",
    hero_cta_vote: "मतदान करा",
    hero_cta_register: "मतदार म्हणून नोंदणी करा",
    stat_uptime: "प्रणाली उपलब्धता",
    stat_turnout: "मतदान टक्केवारी",
    stat_votes: "सील केलेली मते",
    stat_voters: "नोंदणीकृत नागरिक",
    stat_active_elections: "सक्रिय निवडणुका",
    pillar_1_title: "बायोमेट्रिक लाईव्हनेस पडताळणी",
    pillar_1_desc: "बनावट मतदानाला आळा घालण्यासाठी एआय प्रणालीद्वारे पापण्यांची हालचाल आणि नैसर्गिक चेहऱ्याची खात्री केली जाते.",
    pillar_2_title: "मल्टी-फॅक्टर प्रमाणीकरण",
    pillar_2_desc: "नोंदणीकृत मोबाईल नंबरवर पाठवलेल्या सुरक्षित ओटीपीद्वारे खरी ओळख सिद्ध केली जाते.",
    pillar_3_title: "क्रिप्टोग्राफिक डिजिटल पावती",
    pillar_3_desc: "प्रत्येक मतासाठी अपरिवर्तनीय SHA-256 डिजिटल शिक्का तयार होतो ज्यामुळे गुप्त मतदानाची पूर्ण हमी मिळते.",
    election_active: "सक्रिय निवडणूक",
    election_upcoming: "आगामी निवडणूक",
    election_completed: "मतदान संपन्न",
    btn_vote_now: "आता मतदान करा",
    btn_cast_ballot: "मत नोंदवा",
    btn_access_ballot: "मतपत्रिका उघडा",
    btn_view_details: "तपशील पहा",
    btn_download_pdf: "अधिकृत प्रमाणपत्र डाउनलोड करा (PDF)",
    btn_return_dashboard: "डॅशबोर्डवर परत जा",
    btn_retake_photo: "पुन्हा फोटो घ्या",
    btn_take_photo: "आता फोटो घ्या",
    face_scanning: "चेहरा स्कॅन होत आहे...",
    face_blink_prompt: "कृपया सामान्यपणे पापण्यांची हालचाल करा",
    face_turn_prompt: "मान किंचित उजवीकडे वळवा",
    face_look_straight: "कॅमेऱ्याकडे सरळ पहा",
    face_verified: "बायोमेट्रिक ओळख प्रमाणित",
    face_enroll_title: "अधिकृत बायोमेट्रिक फोटो नोंदणी",
    face_verify_title: "बायोमेट्रिक ओळख पडताळणी",
    receipt_title: "अधिकृत मतदान प्रमाणपत्र",
    receipt_hash: "SHA-256 क्रिप्टोग्राफिक सील",
    receipt_verified: "पावती लेजरवर यशस्वीरित्या प्रमाणित",
    notice_secret_ballot: "घटनात्मक गुप्त मतदान संरक्षण (कलम ३२४, भारतीय संविधान)",
    helpline_text: "राष्ट्रीय मतदार हेल्पलाइन: टोल-फ्री १९५०",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('smartvote_lang');
    // If saved is not in supported list (e.g. old 'es' or 'fr'), reset to 'en'
    if (saved && translations[saved]) {
      return saved;
    }
    return 'en';
  });
  const [voiceEnabled, setVoiceEnabled] = useState(false);

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('smartvote_lang', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  const speak = (text) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 0.95;
      utterance.pitch = 1.0;
      if (lang === 'hi') utterance.lang = 'hi-IN';
      else if (lang === 'te') utterance.lang = 'te-IN';
      else if (lang === 'ta') utterance.lang = 'ta-IN';
      else if (lang === 'kn') utterance.lang = 'kn-IN';
      else if (lang === 'bn') utterance.lang = 'bn-IN';
      else if (lang === 'mr') utterance.lang = 'mr-IN';
      else utterance.lang = 'en-IN';
      window.speechSynthesis.speak(utterance);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, speak, voiceEnabled, setVoiceEnabled }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
